Update to Opensearch
arcalot/arcaflow-plugin-opensearch-legacy pull request #1
Opened 2022-12-12 17:53 UTC by dustinblack

## Changes introduced with this PR

This is a series of changes to convert the original elasticsearch plugin functionality to opensearch with corrected and functional tests, as well as to bring the repo format inline with the current template standards.

---
By contributing to this repository, I agree to the [contribution guidelines](https://github.com/arcalot/.github/blob/main/CONTRIBUTING.md).

2022-12-12 18:54 UTC, portante reviewed
Looks good in a quick review.  What's up with `Draft` mode?

2022-12-12 18:54 UTC, portante commented on Dockerfile
> +RUN pip3 install coverage
Poetry generated the `requirements.txt` file under Python 3.9, but it is not clear which version of python `pip3` is, or for that matter, what version `python3` resolves to.

It might be best to just use poetry run these things.  `poetry run ...`

2022-12-13 01:36 UTC, portante requested changes
The builds workflow is hanging.

2022-12-13 06:51 UTC, dustinblack commented on Dockerfile
> +RUN pip3 install coverage
This is verbatim from the template, and it doesn't seem to cause any build or test problems.

https://github.com/arcalot/arcaflow-plugin-template-python/blob/3e280c0a7a3597c69a4fc8b4ecf2bd80fe439028/Dockerfile#L14

https://github.com/arcalot/arcaflow-plugin-template-python/blob/3e280c0a7a3597c69a4fc8b4ecf2bd80fe439028/Dockerfile#L24-L25

I agree that the version ambiguity isn't the best approach here, but I think the change you are suggesting for `poetry run ...` belongs in the template first.

2022-12-13 06:52 UTC, dustinblack commented
> The builds workflow is hanging.

The integration test relies on spinning up an Elasticsearch server in the docker-compose, which requires a lot of memory resources. I'll see if I can thin this down.

2022-12-13 06:59 UTC, dustinblack commented on Dockerfile
> +RUN pip3 install coverage
I adjusted the python commands to be python3.9 explicitly.

2022-12-13 07:31 UTC, dustinblack commented
The build action is failing because of ghcr permissions, which I think have something to do with the `GITHUB_TOKEN`, but I can't seem to figure out what change is needed to correct this. I think @mfleader can help here.

2022-12-13 16:09 UTC, dustinblack commented
IMO the failing Build action can be ignored for now. That automation expects an existing `:latest` tag in the repo, and in this case carpenter has not yet created and pushed that tag from the main branch. When this PR merges, that tag will be created, and the Build action should pass.

2022-12-13 22:55 UTC, portante requested changes

2022-12-13 22:55 UTC, portante commented on .github/workflows/carpenter.yaml
> +    if: github.ref != 'refs/heads/main' && github.event_name != 'release'
Similar concern as in https://github.com/arcalot/arcaflow-plugin-template-python/pull/22#pullrequestreview-1216532755:

So we'll only "build_dev" off of the "head" of `main`, and when the GitHub event name is not "release", but line 23 will release off of any `github.ref` if the `github.event_name` is release and push that release to `main` (see line 31).

Can we put `refs/heads/<name>` in a variable instead, and then we can "release" off of any branch?

2022-12-14 10:36 UTC, dustinblack commented on .github/workflows/carpenter.yaml
> +    if: github.ref != 'refs/heads/main' && github.event_name != 'release'
Please see my [reply in the template repo](https://github.com/arcalot/arcaflow-plugin-template-python/pull/22#discussion_r1048289424) since this is redundant.

2022-12-16 15:15 UTC, mfleader requested changes

2022-12-16 15:15 UTC, mfleader commented on Dockerfile
> +COPY ${package}/ /app/${package}
Now that I think about it, this could probably just be `package` and we would not have to add `ENV package arcaflow_plugin_opensearch`. What do you think?

2022-12-16 15:15 UTC, mfleader commented on arcaflow_plugin_opensearch/opensearch_plugin.py
> +            os = OpenSearch(
Rename to avoid confusion with the Python operating system interface, `os`. If you really want 'os', I think there is a PEP that suggests adding an underscore to the end so that it looks like `os_`. Avoid `_os` or `__os` since pre-pended underscores already have a special meaning.

2023-01-09 16:53 UTC, dustinblack commented on Dockerfile
> +COPY ${package}/ /app/${package}
I thought when we discussed this before you said it was important for the subdirectory to have the unique name for python package behavior. If we _can_ in fact simply change this to `package`, then I think we should first implement that in the template.

2023-01-09 16:58 UTC, dustinblack commented on arcaflow_plugin_opensearch/opensearch_plugin.py
> +            os = OpenSearch(
Fixed

2023-01-10 17:04 UTC, jaredoconnell commented on arcaflow_plugin_opensearch/opensearch_plugin.py
> +        #     raise Exception(f"response status: {resp.meta.status}")
Is there a reason this is commented out? Is it useful, or should it be removed?

2023-01-10 17:12 UTC, dustinblack commented on arcaflow_plugin_opensearch/opensearch_plugin.py
> +        #     raise Exception(f"response status: {resp.meta.status}")
Good catch. It looks like I didn't cleanup completely from debug work. I'll get this fixed.

2023-01-10 17:39 UTC, dustinblack commented on arcaflow_plugin_opensearch/opensearch_plugin.py
> +        #     raise Exception(f"response status: {resp.meta.status}")
This should be taken care of now.

2023-01-10 19:05 UTC, jaredoconnell approved these changes
Looks good to me. The change in the way you specify max ram seems like a good change that is likely to lower the chance of it failing due to memory overage.

2023-01-10 23:34 UTC, portante approved these changes

2023-01-11 11:34 UTC, merged